import argparse
import os
import json
import re


# Dictionnaire des métiers
JOBS = {
    "data engineer": (("data", "engineer"), ("data", "ingénieur")),
    "data architect": (("data", "architect"), ("architect", "si"), ("architect", "it")),
    "data scientist": (("data", "scientist"), ("science", "donnée")),
    "data analyst": (("data", "analyst"), ("data", "analytics")),
    "software engineer": (("software", "engineer"), ("software", "developer"), ("développeur", "logiciel"), ("ingénieur", "logiciel")),
    "devops": ("devops",),
    "data warehousing engineer": ("data", "warehouse", "engineer"),
    "machine learning engineer": (("machine", "learning", "engineer"), ("ml", "engineer")),
    "cloud architect /engineer ": (("cloud", "architect"), ("cloud", "engineer"), ("cloud", "ingénieur"), ("cloud", "engineer"), ("AWS",), ("GCP",), ("azure",)),
    "solution architect": ("solution", "architect"),
    "big data engineer": (("big", "data", "engineer"), ("ingénieur", "big", "data")),
    "big data developer": (("big", "data", "developer"), ("développeur", "big", "data")),
    "data infrastructure engineer": ("data", "infrastructure", "engineer"),
    "data pipeline engineer": ("data", "pipeline", "engineer"),
    "etl developer": ("etl",),
    "business developer": (("business", "developer"), ("sales", "developer")),
    "business analyst": ("business", "analyst"),
    "cybersecurity": (("cyber", "security"), ("cyber", "sécurité"), ("cyber", "risk"), ("cyber", "risque")),
    "sysops": ("sysops",),
    "consultant data": ("data", "consultant"),
}

# Dictionnaire des variables et leurs mots-clés correspondants
skills = {
    "ProgLanguage": [
        "Python", "Java", "C++", "C#", "Scala", " R,", "/R/", " R ", "Julia", "Kotlin", "Bash",
    ],
    "DataBase": [
        "SQL", "NoSQL", "MongoDB", "Cassandra", "Neo4j", "HBase", "Elasticsearch",
    ],
    "DataAnalytics": ["Pandas", "NumPy", " R,", "/R/", " R ", "MATLAB"],
    "BigData": ["Hadoop", "Spark", "Databricks", "Flink", "Apache Airflow"],
    "MachineLearning": [
        "Scikit-Learn", "TensorFlow", "Keras", "PyTorch", "XGBoost", "LightGBM", "CatBoost", "Orange",
    ],
    "DataSerialization": [
        "Avro", "Protocol Buffers", "Json", "XML",
    ],
    "DataVisualisation": [
        "Tableau", "Power BI", "Matplotlib", "Seaborn", "Plotly",
    ],
    "Statistics": [
        "Statistiques Descriptives", "Inférentielles", "Bayesian Statistics", "Statistiques Bayésiennes",
    ],
    "CloudComputing": [
        "AWS", "Azure", "Google Cloud Platform", "GCP", "IBM Cloud", "Alibaba Cloud",
    ],
    "DevTools": ["Git", "Docker", "Jenkins", "Travis CI"],
    "OS": ["Linux", "Windows", "MacOS"],
    "DBMS": [
        "MySQL", "PostgreSQL", "Oracle SQL", "SQL Server", "Snowflake", "BigQuery", "Big Query", "SingleStore",
    ],
    "SoftBigDataProcessing": ["Apache Kafka", "Apache Flink", "HBase", "Cassandra"],
    "Automation": [
        "Ansible", "Kubernetes", "Puppet", "Chef", "Airflow",
    ],
    "InfrastructureAsCode": ["Terraform", "CloudFormation"],
    "NetworkSecurty": ["VPN", "Firewall", "SSL/TLS", "Wireshark"],
    "Virtualisation": ["VMware", "VirtualBox", "Hyper-V"],
    "Containers": ["Docker", "Kubernetes", "OpenShift"],
    "Collaboration": [
        "JIRA", "Confluence", "Slack", "Microsoft Teams", "Teams", "Discord",
    ],
    "Other": [
        "DevOps", "Backend Development", "Big Data", "ML", "Machine Learning", "Statistiques", "Cloud", "CI/CD", "CI / CD",
    ],
    "EnSoftSkils": [
        "Communication", "Teamwork", "Time Management", "Adaptability", "Problem Solving", "Leadership", "Creativity",
        "Empathy", "Collaboration", "Stress Management", "Organization", "Flexibility", "Initiative",
        "Critical Thinking", "Interpersonal Skills"
    ],
}

# Dictionnaire pour la conversion des numéros de départements en noms
places = {
    "02": "Aisne",
    "04": "Alpes-de-Haute-Provence",
    "06": "Alpes-Maritimes",
    "10": "Aube",
    "13": "Bouches-du-Rhône",
    "14": "Calvados",
    "17": "Charente-Maritime",
    "21": "Côte-d'Or",
    "22": "Côtes-d'Armor",
    "23": "Creuse",
    "25": "Doubs",
    "26": "Drôme",
    "27": "Eure",
    "29": "Finistère",
    "30": "Gard",
    "31": "Haute-Garonne",
    "33": "Gironde",
    "34": "Hérault",
    "35": "Ille-et-Vilaine",
    "36": "Indre",
    "37": "Indre-et-Loire",
    "38": "Isère",
    "39": "Jura",
    "40": "Landes",
    "42": "Loire",
    "44": "Loire-Atlantique",
    "45": "Loiret",
    "47": "Lot-et-Garonne",
    "48": "Lozère",
    "49": "Maine-et-Loire",
    "50": "Manche",
    "51": "Marne",
    "53": "Mayenne",
    "54": "Meurthe-et-Moselle",
    "56": "Morbihan",
    "57": "Moselle",
    "59": "Nord",
    "60": "Oise",
    "62": "Pas-de-Calais",
    "63": "Puy-de-Dôme",
    "64": "Pyrénées-Atlantiques",
    "66": "Pyrénées-Orientales",
    "67": "Bas-Rhin",
    "68": "Haut-Rhin",
    "69": "Rhône",
    "70": "Haute-Saône",
    "71": "Saône-et-Loire",
    "72": "Sarthe",
    "73": "Savoie",
    "74": "Haute-Savoie",
    "75": "Paris",
    "76": "Seine-Maritime",
    "77": "Seine-et-Marne",
    "78": "Yvelines",
    "79": "Deux-Sèvres",
    "80": "Somme",
    "81": "Tarn",
    "83": "Var",
    "84": "Vaucluse",
    "85": "Vendée",
    "87": "Haute-Vienne",
    "88": "Vosges",
    "91": "Essonne",
    "92": "Hauts-de-Seine",
    "93": "Seine-Saint-Denis",
    "94": "Val-de-Marne",
    "95": "Val-d'Oise",
    "972": "Martinique",
    "973": "Guyane",
    "974": "Réunion",
    "AIX EN PROVENCE 13": "Aix-en-Provence",
    "ALPES MARITIMES 06": "Alpes-Maritimes",
    "ANGERS 49": "Angers",
    "ANNECY 74": "Annecy",
    "ANSE 69": "Anse",
    "Aarhus": "Aarhus",
    "Abidjan": "Abidjan",
    "Abrest": "Abrest",
    "Agen": "Agen",
    "Aillas": "Aillas",
    "Aimargues": "Aimargues",
    "Aix-En-Provence": "Aix-en-Provence",
    "Aix-en-Provence…+2": "Aix-en-Provence",
    "Aix-les-Bains": "Aix-les-Bains",
    "Ajaccio 2A": "Ajaccio",
    "Alfortville": "Alfortville",
    "Alès": "Alès",
    "Amiens": "Amiens",
    "Amilly": "Amilly",
    "Amnéville": "Amnéville",
    "Ancenis": "Ancenis",
    "Andrézieux-Bouthéon": "Andrézieux-Bouthéon",
    "Angers": "Angers",
    "Anglet": "Anglet",
    "Angoulême": "Angoulême",
    "Annecy-le-Vieux": "Annecy-le-Vieux",
    "Annemasse": "Annemasse",
    "Annot": "Annot",
    "Antibes": "Antibes",
    "Antony": "Antony",
    "Arcueil": "Arcueil",
    "Argancy": "Argancy",
    "Argenteuil": "Argenteuil",
    "Argonay": "Argonay",
    "Arras": "Arras",
    "Ars-sur-Moselle": "Ars-sur-Moselle",
    "Artix": "Artix",
    "Arudy": "Arudy",
    "Asnières-sur-Seine": "Asnières-sur-Seine",
    "Atlanta": "Atlanta",
    "Aubagne": "Aubagne",
    "Aubervilliers": "Aubervilliers",
    "Aubière": "Aubière",
    "Auchel": "Auchel",
    "Aulnay-sous-Bois": "Aulnay-sous-Bois",
    "Auray": "Auray",
    "Aureille": "Aureille",
    "Auxerre": "Auxerre",
    "Auzeville-Tolosane": "Auzeville-Tolosane",
    "Aveiro": "Aveiro",
    "Avelin": "Avelin",
    "Avignon": "Avignon",
    "Avrillé": "Avrillé",
    "AÉROPORT DE PARIS": "Aéroport de Paris",
    "Aéroport Paris-Roissy-Charles-de-Gaulle": "Aéroport Paris-Roissy-Charles-de-Gaulle",
    "Aïcirits-Camou-Suhast": "Aïcirits-Camou-Suhast",
    "BAGNEUX 54": "Bagneux",
    "BELGIQUE": "Belgique",
    "BLAGNAC 31": "Blagnac",
    "BOBIGNY 93": "Bobigny",
    "BOIS COLOMBES 92": "Bois-Colombes",
    "BORDEAUX 33": "Bordeaux",
    "BORDES 64": "Bordes",
    "BOUCHES DU RHÔNE 13": "Bouches-du-Rhône",
    "BREANCON 95": "Breancon",
    "BRUNOY 91": "Brunoy",
    "BUSSY ST GEORGES 77": "Bussy-Saint-Georges",
    "Bagneux": "Bagneux",
    "Bagnolet": "Bagnolet",
    "Bagnols-sur-Cèze": "Bagnols-sur-Cèze",
    "Baie-Mahault": "Baie-Mahault",
    "Ballancourt-sur-Essonne": "Ballancourt-sur-Essonne",
    "Balma": "Balma",
    "Barcelona": "Barcelona",
    "Barcelone": "Barcelone",
    "Barembach": "Barembach",
    "Bayeux": "Bayeux",
    "Bayonne": "Bayonne",
    "Bazainville": "Bazainville",
    "Beaumont-Hague": "Beaumont-Hague",
    "Beaumont-le-Roger": "Beaumont-le-Roger",
    "Beaune": "Beaune",
    "Beauvais": "Beauvais",
    "Belfort": "Belfort",
    "Belgrade": "Belgrade",
    "Bellevigny": "Bellevigny",
    "Belleville": "Belleville",
    "Belley": "Belley",
    "Benfeld": "Benfeld",
    "Bengaluru, Manila": "Bengaluru",
    "Berlin": "Berlin",
    "Bernin": "Bernin",
    "Berné": "Berné",
    "Besancon": "Besancon",
    "Besançon": "Besançon",
    "Bessines": "Bessines",
    "Bessines-sur-Gartempe": "Bessines-sur-Gartempe",
    "Beynost": "Beynost",
    "Bezannes": "Bezannes",
    "Bezons": "Bezons",
    "Biarritz": "Biarritz",
    "Bidart": "Bidart",
    "Billy-Berclau": "Billy-Berclau",
    "Biot": "Biot",
    "Bischheim": "Bischheim",
    "Bischwiller": "Bischwiller",
    "Blagnac": "Blagnac",
    "Blainville-sur-Orne": "Blainville-sur-Orne",
    "Blois": "Blois",
    "Blyes": "Blyes",
    "Bobigny": "Bobigny",
    "Bois": "Bois",
    "Bois-Colombes": "Bois-Colombes",
    "Bois-Guillaume": "Bois-Guillaume",
    "Bon-Encontre": "Bon-Encontre",
    "Bonchamp-lès-Laval": "Bonchamp-lès-Laval",
    "Bondoufle": "Bondoufle",
    "Bondues": "Bondues",
    "Bordeaux, Lyon…+1": "Bordeaux",
    "Bordes": "Bordes",
    "Boucau": "Boucau",
    "Bouguenais": "Bouguenais",
    "Boulogne-Billancourt": "Boulogne-Billancourt",
    "Boulogne-Billancourt…+1": "Boulogne-Billancourt",
    "Boulogne-Billancourt…+15": "Boulogne-Billancourt",
    "Boulogne-Billancourt…+2": "Boulogne-Billancourt",
    "Boulogne-Billancourt…+7": "Boulogne-Billancourt",
    "Boulogne-sur-Mer": "Boulogne-sur-Mer",
    "Bourg-en-Bresse": "Bourg-en-Bresse",
    "Bourg-lès-Valence": "Bourg-lès-Valence",
    "Bourges": "Bourges",
    "Bourgoin-Jallieu": "Bourgoin-Jallieu",
    "Bourguébus": "Bourguébus",
    "Bremen": "Bremen",
    "Bresles": "Bresles",
    "Brest": "Brest",
    "Breuil-le-Sec": "Breuil-le-Sec",
    "Brienne-le-Château": "Brienne-le-Château",
    "Briennon": "Briennon",
    "Brignais": "Brignais",
    "Brindas": "Brindas",
    "Brisbane": "Brisbane",
    "Brive-la-Gaillarde": "Brive-la-Gaillarde",
    "Bron": "Bron",
    "Bruges": "Bruges",
    "Bruguières": "Bruguières",
    "Brumath": "Brumath",
    "Brunoy": "Brunoy",
    "Brussels": "Brussels",
    "Bruxelles": "Bruxelles",
    "Bruyères-le-Châtel": "Bruyères-le-Châtel",
    "Bruz": "Bruz",
    "Bry-sur-Marne": "Bry-sur-Marne",
    "Brécé": "Brécé",
    "Brétigny-sur-Orge": "Brétigny-sur-Orge",
    "Buc": "Buc",
    "Bucharest": "Bucharest",
    "Budweis": "Budweis",
    "Bussigny": "Bussigny",
    "Bussy-Saint-Georges": "Bussy-Saint-Georges",
    "Bussy-Saint-Martin": "Bussy-Saint-Martin",
    "Bègles": "Bègles",
    "Béthune": "Béthune",
    "CESSON SEVIGNE 35": "Cesson-Sévigné",
    "CHARTRES 28": "Chartres",
    "CHATEAULIN 29": "Châteaulin",
    "CHATELLERAULT 86": "Châtellerault",
    "CHATENAY MALABRY 92": "Châtenay-Malabry",
    "CHESSY 77": "Chessy",
    "CLERMONT FERRAND 63": "Clermont-Ferrand",
    "CLICHY 92": "Clichy",
    "CONFLANS STE HONORINE 78": "Conflans-Sainte-Honorine",
    "CONSULTING GROUPE": "Consulting Groupe",
    "CORBEIL 51": "Corbeil",
    "COURBEVOIE 92": "Courbevoie",
    "COURNON D AUVERGNE 63": "Cournon-d'Auvergne",
    "CROIX 90": "Croix",
    "Cachan": "Cachan",
    "Caen": "Caen",
    "Cagnes-sur-Mer": "Cagnes-sur-Mer",
    "Calais": "Calais",
    "Caluire-et-Cuire": "Caluire-et-Cuire",
    "Camon": "Camon",
    "Cannes": "Cannes",
    "Canéjan": "Canéjan",
    "Caouënnec-Lanvézéac": "Caouënnec-Lanvézéac",
    "Cappelle-en-Pévèle": "Cappelle-en-Pévèle",
    "Carcassonne": "Carcassonne",
    "Carling": "Carling",
    "Carquefou": "Carquefou",
    "Carrières-sur-Seine": "Carrières-sur-Seine",
    "Carros": "Carros",
    "Casablanca": "Casablanca",
    "Castelculier": "Castelculier",
    "Castelnau-le-Lez": "Castelnau-le-Lez",
    "Castres": "Castres",
    "Caumont-sur-Durance": "Caumont-sur-Durance",
    "Cavaillon": "Cavaillon",
    "Cedar Rapids": "Cedar Rapids",
    "Celle-Lévescault": "Celle-Lévescault",
    "Centrale nucléaire du Tricastin": "Centrale nucléaire du Tricastin",
    "Ceret": "Ceret",
    "Cergy": "Cergy",
    "Cergy-Pontoise": "Cergy-Pontoise",
    "Cernay-lès-Reims": "Cernay-lès-Reims",
    "Cesson-Sévigné": "Cesson-Sévigné",
    "Cestas": "Cestas",
    "Ceyzériat": "Ceyzériat",
    "Chalampé": "Chalampé",
    "Challes-les-Eaux": "Challes-les-Eaux",
    "Chalon-sur-Saône": "Chalon-sur-Saône",
    "Chambourcy": "Chambourcy",
    "Chambre": "Chambre",
    "Chambéry": "Chambéry",
    "Champigneulles": "Champigneulles",
    "Champigny": "Champigny",
    "Champlan": "Champlan",
    "Champs-sur-Marne": "Champs-sur-Marne",
    "Chantilly": "Chantilly",
    "Chaponnay": "Chaponnay",
    "Charenton-le-Pont": "Charenton-le-Pont",
    "Chartres": "Chartres",
    "Chartres-de-Bretagne": "Chartres-de-Bretagne",
    "Chasseneuil-du-Poitou": "Chasseneuil-du-Poitou",
    "Chassieu": "Chassieu",
    "Chatou": "Chatou",
    "Chaumont": "Chaumont",
    "Chauray": "Chauray",
    "Chemilly-sur-Yonne": "Chemilly-sur-Yonne",
    "Cherbourg-Octeville": "Cherbourg-Octeville",
    "Cherbourg-en-Cotentin": "Cherbourg-en-Cotentin",
    "Chessy": "Chessy",
    "Chevigny-Saint-Sauveur": "Chevigny-Saint-Sauveur",
    "Chevilly": "Chevilly",
    "Chevilly-Larue": "Chevilly-Larue",
    "Chiché": "Chiché",
    "Choisy-le-Roi": "Choisy-le-Roi",
    "Cholet": "Cholet",
    "Chusclan": "Chusclan",
    "Château-Gontier-sur-Mayenne": "Château-Gontier-sur-Mayenne",
    "Château-Thierry": "Château-Thierry",
    "Châteaufort": "Châteaufort",
    "Châteauneuf-du-Rhône": "Châteauneuf-du-Rhône",
    "Châteauroux": "Châteauroux",
    "Châtellerault": "Châtellerault",
    "Châtenay-Malabry": "Châtenay-Malabry",
    "Châtillon": "Châtillon",
    "Châtillon-le-Duc": "Châtillon-le-Duc",
    "City of Industry": "City of Industry",
    "Clamart": "Clamart",
    "Clermont-Ferrand": "Clermont-Ferrand",
    "Clichy": "Clichy",
    "Cluses": "Cluses",
    "Cognac": "Cognac",
    "Colmar": "Colmar",
    "Cologne": "Cologne",
    "Colombelles": "Colombelles",
    "Colombes": "Colombes",
    "Colomiers": "Colomiers",
    "Compiègne": "Compiègne",
    "Concarneau": "Concarneau",
    "Contrisson": "Contrisson",
    "Corbas": "Corbas",
    "Corbeil-Essonnes": "Corbeil-Essonnes",
    "Cormelles-le-Royal": "Cormelles-le-Royal",
    "Cornebarrieu": "Cornebarrieu",
    "Courbevoie": "Courbevoie",
    "Courcouronnes": "Courcouronnes",
    "Couëron": "Couëron",
    "Coëx": "Coëx",
    "Cracow": "Cracow",
    "Cran-Gevrier": "Cran-Gevrier",
    "Craponne": "Craponne",
    "Croissy-Beaubourg": "Croissy-Beaubourg",
    "Croissy-sur-Seine": "Croissy-sur-Seine",
    "Croix": "Croix",
    "Crolles": "Crolles",
    "Créteil": "Créteil",
    "Cugnaux": "Cugnaux",
    "Cénac": "Cénac",
    "DIJON 21": "Dijon",
    "DIRECTION DES SYSTEMES D'INFORMATIONS": "Direction des systèmes d'informations",
    "DIRECTION TERRITORIALE DE ROUEN": "Direction territoriale de Rouen",
    "Dallas": "Dallas",
    "Dardilly": "Dardilly",
    "Denver": "Denver",
    "Dhaka": "Dhaka",
    "Dieppe": "Dieppe",
    "Dijon": "Dijon",
    "Dinard": "Dinard",
    "Dinsheim-sur-Bruche": "Dinsheim-sur-Bruche",
    "Dole": "Dole",
    "Domont": "Domont",
    "Dompierre-sur-Yon": "Dompierre-sur-Yon",
    "Douai": "Douai",
    "Drancy": "Drancy",
    "Dreux": "Dreux",
    "Drogenbos": "Drogenbos",
    "Dubai": "Dubai",
    "Dublin": "Dublin",
    "Dunkerque": "Dunkerque",
    "Décines-Charpieu": "Décines-Charpieu",
    "ECHIROLLES 38": "Échirolles",
    "ELANCOURT 78": "Élancourt",
    "ERAGNY 95": "Éragny",
    "ERINGHEM 59": "Eringhem",
    "ESSONNE 91": "Essonne",
    "EVRY COURCOURONNES 91": "Évry-Courcouronnes",
    "Eaubonne": "Eaubonne",
    "Ecquevilly": "Ecquevilly",
    "Elven": "Elven",
    "Enghien-les-Bains": "Enghien-les-Bains",
    "Ennezat": "Ennezat",
    "Entzheim, Montreal": "Entzheim",
    "Ernolsheim-Bruche": "Ernolsheim-Bruche",
    "Erstein": "Erstein",
    "Estrées-Saint-Denis": "Estrées-Saint-Denis",
    "Esvres": "Esvres",
    "Eu": "Eu",
    "Eybens": "Eybens",
    "FONTENAY SOUS BOIS 94": "Fontenay-sous-Bois",
    "Fairbanks": "Fairbanks",
    "Faulquemont": "Faulquemont",
    "Faverges-Seythenex": "Faverges-Seythenex",
    "Figeac": "Figeac",
    "Fin": "Fin",
    "Flers": "Flers",
    "Fleurance": "Fleurance",
    "Fleury-Mérogis": "Fleury-Mérogis",
    "Fleury-les-Aubrais": "Fleury-les-Aubrais",
    "Florange": "Florange",
    "Foix": "Foix",
    "Fontaine": "Fontaine",
    "Fontaine-le-Comte": "Fontaine-le-Comte",
    "Fontainebleau, Singapore": "Fontainebleau",
    "Fontenay-le-Comte": "Fontenay-le-Comte",
    "Fontenay-sous-Bois": "Fontenay-sous-Bois",
    "Fort-de-France": "Fort-de-France",
    "Fos-sur-Mer": "Fos-sur-Mer",
    "Frace": "Frace",
    "Francheville": "Francheville",
    "Franconville": "Franconville",
    "French Guiana": "French Guiana",
    "French Polynesia": "French Polynesia",
    "Fréjus": "Fréjus",
    "Frépillon": "Frépillon",
    "Fuveau": "Fuveau",
    "GARONNE (HAUTE) 31": "Haute-Garonne",
    "GENNEVILLIERS 92": "Gennevilliers",
    "GONFREVILLE L ORCHER 76": "Gonfreville-l'Orcher",
    "GRAND EST": "Grand Est",
    "GRENOBLE 38": "Grenoble",
    "GROUPE VYV": "Groupe VYV",
    "GUYANCOURT 78": "Guyancourt",
    "Gaillard": "Gaillard",
    "Gap": "Gap",
    "Garches": "Garches",
    "Gavaudun": "Gavaudun",
    "Gazeran": "Gazeran",
    "Gdansk": "Gdansk",
    "Gdańsk": "Gdańsk",
    "Genas": "Genas",
    "Geneva": "Geneva",
    "Gennevilliers": "Gennevilliers",
    "Gentilly": "Gentilly",
    "Gençay": "Gençay",
    "Gevrey-Chambertin": "Gevrey-Chambertin",
    "Giberville": "Giberville",
    "Gif-sur-Yvette": "Gif-sur-Yvette",
    "Gières": "Gières",
    "Gland": "Gland",
    "Glasgow": "Glasgow",
    "Gonesse": "Gonesse",
    "Gonfreville-l'Orcher": "Gonfreville-l'Orcher",
    "Gouesnou": "Gouesnou",
    "Gournay-sur-Marne": "Gournay-sur-Marne",
    "Gradignan": "Gradignan",
    "Gramat": "Gramat",
    "Granada": "Granada",
    "Grand Est": "Grand Est",
    "Grand Prairie": "Grand Prairie",
    "Grand": "Grand",
    "Greater Le Havre Area": "Le Havre",
    "Greater Lille Metropolitan Area": "Lille",
    "Greater Lyon Area": "Lyon",
    "Greater Marseille Metropolitan Area": "Marseille",
    "Greater Nantes Metropolitan Area": "Nantes",
    "Greater Nice Metropolitan Area": "Nice",
    "Greater Nimes Area": "Nimes",
    "Greater Paris Metropolitan Region": "Paris",
    "Greater Pau Area": "Pau",
    "Greater Rouen Metropolitan Area": "Rouen",
    "Greater Saint-Etienne Metropolitan Area": "Saint-Étienne",
    "Greater Saint-Nazaire Area": "Saint-Nazaire",
    "Greater Strasbourg Metropolitan Area": "Strasbourg",
    "Greater Toulouse Metropolitan Area": "Toulouse",
    "Greater Tours Area": "Tours",
    "Grenoble": "Grenoble",
    "Grigny": "Grigny",
    "Guadeloupe": "Guadeloupe",
    "Gueugnon": "Gueugnon",
    "Gueux": "Gueux",
    "Guipavas": "Guipavas",
    "Guyancourt": "Guyancourt",
    "Guérande": "Guérande",
    "Guéreins": "Guéreins",
    "Gémenos": "Gémenos",
    "HAUTS DE SEINE 92": "Hauts-de-Seine",
    "Hagenberg im Mühlkreis": "Hagenberg im Mühlkreis",
    "Haguenau": "Haguenau",
    "Hanover": "Hanover",
    "Hellemmes-Lille": "Hellemmes-Lille",
    "Hem": "Hem",
    "Hradec Kralove": "Hradec Kralove",
    "Huningue": "Huningue",
    "HÉRAULT 34": "Hérault",
    "Héry": "Héry",
    "ILE-DE-FRANCE": "Île-de-France",
    "ILLE ET VILAINE 35": "Ille-et-Vilaine",
    "INDRE ET LOIRE 37": "Indre-et-Loire",
    "ISSY LES MOULINEAUX 92": "Issy-les-Moulineaux",
    "IT": "IT",
    "IVRY SUR SEINE 94": "Ivry-sur-Seine",
    "Illkirch-Graffenstaden": "Illkirch-Graffenstaden",
    "Irigny": "Irigny",
    "Isneauville": "Isneauville",
    "Issoire": "Issoire",
    "Issoudun": "Issoudun",
    "Issus": "Issus",
    "Issy-Les-Moulineaux": "Issy-les-Moulineaux",
    "Issy-les-Moulineaux": "Issy-les-Moulineaux",
    "Istres": "Istres",
    "Itteville": "Itteville",
    "Ivry-sur-Seine": "Ivry-sur-Seine",
    "Janzé": "Janzé",
    "Jarnac": "Jarnac",
    "Jarrie": "Jarrie",
    "Jeumont": "Jeumont",
    "Jičín": "Jičín",
    "Joinville-le-Pont": "Joinville-le-Pont",
    "Jonage": "Jonage",
    "Jouy-en-Josas": "Jouy-en-Josas",
    "Joué-lés-Tours": "Joué-lés-Tours",
    "KIRCHBERG 68": "Kirchberg",
    "Kaiserslautern": "Kaiserslautern",
    "Kharkiv": "Kharkiv",
    "Kourou GF": "Kourou",
    "Kunheim": "Kunheim",
    "L'Isle-Jourdain": "L'Isle-Jourdain",
    "L'Isle-d'Abeau": "L'Isle-d'Abeau",
    "L'Isle-d'Espagnac": "L'Isle-d'Espagnac",
    "LA CHEVROLIERE 44": "La Chevrolière",
    "LA CIOTAT 13": "La Ciotat",
    "LA GARENNE COLOMBES 92": "La Garenne-Colombes",
    "LA ROCHELLE 70": "La Rochelle",
    "LANDERNEAU 29": "Landerneau",
    "LAVAL 53": "Laval",
    "LE BAR SUR LOUP 06": "Le Bar-sur-Loup",
    "LE BOULOU 66": "Le Boulou",
    "LE PLESSIS ROBINSON 92": "Le Plessis-Robinson",
    "LEVALLOIS PERRET 92": "Levallois-Perret",
    "LEZENNES 59": "Lezennes",
    "LILLE 59": "Lille",
    "LIMONEST 69": "Limonest",
    "LISIEUX 14": "Lisieux",
    "LOIRE ATLANTIQUE 44": "Loire-Atlantique",
    "LONGJUMEAU 91": "Longjumeau",
    "LUXEMBOURG (FRONTALIER)": "Luxembourg",
    "LYON 01 69": "Lyon",
    "LYON 05 69": "Lyon",
    "La Balme-les-Grottes": "La Balme-les-Grottes",
    "La Bastide-des-Jourdans": "La Bastide-des-Jourdans",
    "La Chapelle-Saint-Luc": "La Chapelle-Saint-Luc",
    "La Chapelle-des-Fougeretz": "La Chapelle-des-Fougeretz",
    "La Chapelle-sur-Erdre": "La Chapelle-sur-Erdre",
    "La Chaux-de-Fonds": "La Chaux-de-Fonds",
    "La Chevrolière": "La Chevrolière",
    "La Ciotat": "La Ciotat",
    "La Courneuve": "La Courneuve",
    "La Defense": "La Defense",
    "La Défense…+1": "La Défense",
    "La Ferté-Saint-Aubin": "La Ferté-Saint-Aubin",
    "La Garde": "La Garde",
    "La Garenne-Colombes": "La Garenne-Colombes",
    "La Hague": "La Hague",
    "La Madeleine": "La Madeleine",
    "La Magdelaine-sur-Tarn": "La Magdelaine-sur-Tarn",
    "La Marne": "La Marne",
    "La Motte-Servolex": "La Motte-Servolex",
    "La Ricamarie": "La Ricamarie",
    "La Roche-sur-Yon": "La Roche-sur-Yon",
    "La Rochelle": "La Rochelle",
    "La Seyne-sur-Mer": "La Seyne-sur-Mer",
    "La Teste-de-Buch": "La Teste-de-Buch",
    "La Verpillière": "La Verpillière",
    "La Verrière": "La Verrière",
    "La Vineuse": "La Vineuse",
    "Labège": "Labège",
    "Lambersart": "Lambersart",
    "Lamentin GP": "Lamentin",
    "Lamorlaye": "Lamorlaye",
    "Langon": "Langon",
    "Lannion": "Lannion",
    "Lanvallay": "Lanvallay",
    "Larmor-Plage": "Larmor-Plage",
    "Lattes": "Lattes",
    "Laudun-l'Ardoise": "Laudun-l'Ardoise",
    "Launaguet": "Launaguet",
    "Lausanne": "Lausanne",
    "Laval": "Laval",
    "Laxou": "Laxou",
    "Le Bar-sur-Loup": "Le Bar-sur-Loup",
    "Le Bignon": "Le Bignon",
    "Le Bourget-Du-Lac": "Le Bourget-Du-Lac",
    "Le Bourget-du-Lac": "Le Bourget-du-Lac",
    "Le Bouscat": "Le Bouscat",
    "Le Chesnay": "Le Chesnay",
    "Le Chesnay-Rocquencourt": "Le Chesnay-Rocquencourt",
    "Le Coudray": "Le Coudray",
    "Le Creusot": "Le Creusot",
    "Le Fuilet": "Le Fuilet",
    "Le Haillan": "Le Haillan",
    "Le Havre": "Le Havre",
    "Le Kremlin-Bicêtre": "Le Kremlin-Bicêtre",
    "Le Lamentin": "Le Lamentin",
    "Le Mans": "Le Mans",
    "Le Pecq": "Le Pecq",
    "Le Perray-en-Yvelines": "Le Perray-en-Yvelines",
    "Le Petit-Quevilly": "Le Petit-Quevilly",
    "Le Plessis-Robinson": "Le Plessis-Robinson",
    "Le Pont-de-Claix": "Le Pont-de-Claix",
    "Le Pouzin": "Le Pouzin",
    "Le Pré-Saint-Gervais": "Le Pré-Saint-Gervais",
    "Le Puy-Sainte-Réparade": "Le Puy-Sainte-Réparade",
    "Le Quesnoy": "Le Quesnoy",
    "Le Relecq-Kerhuon": "Le Relecq-Kerhuon",
    "Le Touquet-Paris-Plage": "Le Touquet-Paris-Plage",
    "Le Vaudreuil": "Le Vaudreuil",
    "Le Vésinet": "Le Vésinet",
    "Lens": "Lens",
    "Les Achards": "Les Achards",
    "Les Alluets-le-Roi": "Les Alluets-le-Roi",
    "Les Angles": "Les Angles",
    "Les Clayes-sous-Bois": "Les Clayes-sous-Bois",
    "Les Herbiers": "Les Herbiers",
    "Les Lilas": "Les Lilas",
    "Les Loges-en-Josas": "Les Loges-en-Josas",
    "Les Mureaux": "Les Mureaux",
    "Les Sables-d'Olonne": "Les Sables-d'Olonne",
    "Les Ulis": "Les Ulis",
    "Lesquin": "Lesquin",
    "Lestrem": "Lestrem",
    "Levallois-Perret": "Levallois-Perret",
    "Leyment": "Leyment",
    "Libourne": "Libourne",
    "Limay": "Limay",
    "Limeil-Brévannes": "Limeil-Brévannes",
    "Limoges": "Limoges",
    "Limours": "Limours",
    "Lingolsheim": "Lingolsheim",
    "Linz": "Linz",
    "Lisbon": "Lisbon",
    "Lisieux": "Lisieux",
    "Lisses": "Lisses",
    "Lièpvre": "Lièpvre",
    "Lognes": "Lognes",
    "London": "London",
    "Longué-Jumelles": "Longué-Jumelles",
    "Loos": "Loos",
    "Lorgues": "Lorgues",
    "Lorient": "Lorient",
    "Lormont": "Lormont",
    "Loughton": "Loughton",
    "Louveciennes": "Louveciennes",
    "Ludon-Médoc": "Ludon-Médoc",
    "Ludres": "Ludres",
    "Lusignan": "Lusignan",
    "Lyon 1er": "Lyon",
    "Lyon 2e": "Lyon",
    "Lyon 3e": "Lyon",
    "Lyon 4e": "Lyon",
    "Lyon 5e": "Lyon",
    "Lyon 6e": "Lyon",
    "Lyon 7e": "Lyon",
    "Lyon 8e": "Lyon",
    "Lyon 9e": "Lyon",
    "Lyon, Aix-en-Provence": "Lyon",
    "Lys-lez-Lannoy": "Lys-lez-Lannoy",
    "MAGNY LES HAMEAUX 78": "Magny-les-Hameaux",
    "MAISONS ALFORT 94": "Maisons-Alfort",
    "MALAKOFF 92": "Malakoff",
    "MALAKOFF": "Malakoff",
    "MANCHE 50": "Manche",
    "MAROC": "Maroc",
    "MARSEILLE 07 13": "Marseille",
    "MASSY 91": "Massy",
    "MERIGNAC 33": "Mérignac",
    "MEUDON 92": "Meudon",
    "MEYLAN 38": "Meylan",
    "MONACO": "Monaco",
    "MONTIGNY LE BRETONNEUX 78": "Montigny-le-Bretonneux",
    "MONTPELLIER 34": "Montpellier",
    "MONTREAL 32": "Montreal",
    "MONTROUGE 92": "Montrouge",
    "Madrid": "Madrid",
    "Magny-les-Hameaux": "Magny-les-Hameaux",
    "Maidenhead": "Maidenhead",
    "Maisons-Alfort": "Maisons-Alfort",
    "Maisons-Laffitte, Barcelona…+1": "Maisons-Laffitte",
    "Maizières-lès-Metz": "Maizières-lès-Metz",
    "Malakoff": "Malakoff",
    "Malemort": "Malemort",
    "Malemort-sur-Corrèze": "Malemort-sur-Corrèze",
    "Mamoudzou YT": "Mamoudzou",
    "Mandelieu-la-Napoule": "Mandelieu-la-Napoule",
    "Mantes-la-Jolie": "Mantes-la-Jolie",
    "Mantes-la-Ville": "Mantes-la-Ville",
    "Marcq-En-Barœul": "Marcq-En-Barœul",
    "Marcq-en-Baroeul": "Marcq-en-Baroeul",
    "Marcq-en-Barœul": "Marcq-en-Barœul",
    "Marcy-L'étoile": "Marcy-L'étoile",
    "Marcy-l'Étoile": "Marcy-l'Étoile",
    "Marignane": "Marignane",
    "Marly-la-Ville": "Marly-la-Ville",
    "Marly-le-Roi": "Marly-le-Roi",
    "Marnaz": "Marnaz",
    "Marne-la-Vallée": "Marne-la-Vallée",
    "Marquette-lez-Lille": "Marquette-lez-Lille",
    "Marseille 1er": "Marseille",
    "Marseille 2e": "Marseille",
    "Marseille 3e": "Marseille",
    "Marseille 4e": "Marseille",
    "Marseille 5e": "Marseille",
    "Marseille 6e": "Marseille",
    "Marseille 7e": "Marseille",
    "Marseille 8e": "Marseille",
    "Marseille 9e": "Marseille",
    "Martinique": "Martinique",
    "Massieux": "Massieux",
    "Massy": "Massy",
    "Matougues": "Matougues",
    "Mauguio": "Mauguio",
    "Maulévrier": "Maulévrier",
    "Mayenne": "Mayenne",
    "Meaux": "Meaux",
    "Melbourne, Sydney": "Melbourne",
    "Melesse": "Melesse",
    "Melun": "Melun",
    "Mende": "Mende",
    "Mer": "Mer",
    "Mercin-et-Vaux": "Mercin-et-Vaux",
    "Messimy": "Messimy",
    "Metz": "Metz",
    "Meudon, Limonest": "Meudon",
    "Meulan": "Meulan",
    "Meylan": "Meylan",
    "Meythet": "Meythet",
    "Meyzieu": "Meyzieu",
    "Milan": "Milan",
    "Millau": "Millau",
    "Minneapolis": "Minneapolis",
    "Mirville": "Mirville",
    "Moirans": "Moirans",
    "Moissy-Cramayel": "Moissy-Cramayel",
    "Molsheim": "Molsheim",
    "Monaco": "Monaco",
    "Mondeville": "Mondeville",
    "Mondonville": "Mondonville",
    "Mont-Saint-Aignan": "Mont-Saint-Aignan",
    "Mont-de-Marsan": "Mont-de-Marsan",
    "Mont-lès-Neufchâteau": "Mont-lès-Neufchâteau",
    "Montagnat": "Montagnat",
    "Montaigu": "Montaigu",
    "Montargis": "Montargis",
    "Montauban": "Montauban",
    "Montbonnot-Saint-Martin": "Montbonnot-Saint-Martin",
    "Monte-Carlo": "Monte-Carlo",
    "Monteils": "Monteils",
    "Montereau-Fault-Yonne": "Montereau-Fault-Yonne",
    "Montereau-sur-le-Jard": "Montereau-sur-le-Jard",
    "Montesquieu-Volvestre": "Montesquieu-Volvestre",
    "Montesson": "Montesson",
    "Montigny-le-Bretonneux": "Montigny-le-Bretonneux",
    "Montluel": "Montluel",
    "Montluçon": "Montluçon",
    "Montmerle-sur-Saône": "Montmerle-sur-Saône",
    "Montoir-de-Bretagne": "Montoir-de-Bretagne",
    "Montornès del Vallès": "Montornès del Vallès",
    "Montrabé": "Montrabé",
    "Montreal, La Défense": "Montreal",
    "Montreuil": "Montreuil",
    "Montrouge": "Montrouge",
    "Montréal": "Montréal",
    "Montréal-la-Cluse": "Montréal-la-Cluse",
    "Montélimar": "Montélimar",
    "Montévrain": "Montévrain",
    "Morangis": "Morangis",
    "Morsang-sur-Orge": "Morsang-sur-Orge",
    "Morschwiller-le-Bas": "Morschwiller-le-Bas",
    "Mortain": "Mortain",
    "Mougins": "Mougins",
    "Mouguerre": "Mouguerre",
    "Moussy-le-Vieux": "Moussy-le-Vieux",
    "Mulhouse": "Mulhouse",
    "Mumbai": "Mumbai",
    "Mundolsheim": "Mundolsheim",
    "Munich": "Munich",
    "Myrtle Point": "Myrtle Point",
    "Málaga": "Málaga",
    "Mâcon": "Mâcon",
    "Mérignac": "Mérignac",
    "Méru": "Méru",
    "NANTERRE 92": "Nanterre",
    "NANTES 44": "Nantes",
    "NEUILLY SUR SEINE 92": "Neuilly-sur-Seine",
    "NICE 06": "Nice",
    "NIORT 79": "Niort",
    "NOGENT SUR SEINE 10": "Nogent-sur-Seine",
    "NORD 59": "Nord",
    "Nancy": "Nancy",
    "Nanterre": "Nanterre",
    "Nançay": "Nançay",
    "Narbonne": "Narbonne",
    "Nersac": "Nersac",
    "Neuilly-Sur-Seine": "Neuilly-sur-Seine",
    "Neuilly-sur-Marne": "Neuilly-sur-Marne",
    "Neuilly-sur-Seine": "Neuilly-sur-Seine",
    "New Caledonia": "New Caledonia",
    "New Delhi": "New Delhi",
    "New Territories": "New Territories",
    "New York": "New York",
    "Nice": "Nice",
    "Niort": "Niort",
    "Nogent-sur-Marne": "Nogent-sur-Marne",
    "Nogent-sur-Seine": "Nogent-sur-Seine",
    "Noida": "Noida",
    "Noisiel": "Noisiel",
    "Noisy-le-Grand": "Noisy-le-Grand",
    "Noisy-le-Sec": "Noisy-le-Sec",
    "Normandie": "Normandie",
    "Norroy-le-Veneur": "Norroy-le-Veneur",
    "Nouans-les-Fontaines": "Nouans-les-Fontaines",
    "Nouméa NC": "Nouméa",
    "Noyal-sur-Vilaine": "Noyal-sur-Vilaine",
    "Noyelles-sous-Lens": "Noyelles-sous-Lens",
    "Noyon": "Noyon",
    "Nîmes": "Nîmes",
    "OCCITANIE": "Occitanie",
    "OISE 60": "Oise",
    "ORLEANS 45": "Orléans",
    "ORLY 94": "Orly",
    "Oberhausbergen": "Oberhausbergen",
    "Obernai": "Obernai",
    "Octeville-sur-Mer": "Octeville-sur-Mer",
    "Olivet": "Olivet",
    "Ollioules": "Ollioules",
    "Oloron-Sainte-Marie": "Oloron-Sainte-Marie",
    "Onet-le-Château": "Onet-le-Château",
    "Onnaing": "Onnaing",
    "Orcier": "Orcier",
    "Orleans": "Orléans",
    "Orly": "Orly",
    "Orléans": "Orléans",
    "Orsay": "Orsay",
    "Orthez": "Orthez",
    "Orvault": "Orvault",
    "Ottignies-Louvain-la-Neuve": "Ottignies-Louvain-la-Neuve",
    "Our": "Our",
    "Ouroux-sur-Saône": "Ouroux-sur-Saône",
    "Oô": "Oô",
    "PARIS (DEPT.) 75": "Paris",
    "PARIS 01 75": "Paris",
    "PARIS 08 75": "Paris",
    "PARIS 09 75": "Paris",
    "PARIS 15 75": "Paris",
    "PARIS 75": "Paris",
    "PAU 64": "Pau",
    "PLAISIR 78": "Plaisir",
    "PORCIEU AMBLAGNIEU 38": "Porcieu-Amblagnieu",
    "PRINCIPAUTÉ DE MONACO": "Principauté de Monaco",
    "PUTEAUX 92": "Puteaux",
    "PYRÉNÉES ATLANTIQUES 64": "Pyrénées-Atlantiques",
    "Pacé": "Pacé",
    "Palaiseau": "Palaiseau",
    "Pamplona": "Pamplona",
    "Pantin, Paris": "Pantin",
    "Paray-Vieille-Poste": "Paray-Vieille-Poste",
    "Paris - La Défense": "Paris",
    "Paris 0e": "Paris",
    "Paris 1e": "Paris",
    "Paris 1er": "Paris",
    "Paris 2e": "Paris",
    "Paris 3e": "Paris",
    "Paris 4e": "Paris",
    "Paris 5e": "Paris",
    "Paris 6e": "Paris",
    "Paris 7e": "Paris",
    "Paris 8e": "Paris",
    "Paris 9e": "Paris",
    "Paris La Défense": "Paris",
    "Paris, Ghent": "Paris",
    "Pau": "Pau",
    "Pays de la Loire": "Pays de la Loire",
    "Pernes-les-Fontaines": "Pernes-les-Fontaines",
    "Perpignan": "Perpignan",
    "Pertuis": "Pertuis",
    "Pessac": "Pessac",
    "Peterborough": "Peterborough",
    "Petersbach": "Petersbach",
    "Petit-Caux": "Petit-Caux",
    "Pierrelatte": "Pierrelatte",
    "Piffonds": "Piffonds",
    "Pilsen, Prague": "Pilsen",
    "Pimbo": "Pimbo",
    "Plaisir": "Plaisir",
    "Pleucadeuc": "Pleucadeuc",
    "Plouzané": "Plouzané",
    "Poissy": "Poissy",
    "Poitiers": "Poitiers",
    "Poligny": "Poligny",
    "Pont-Évêque": "Pont-Évêque",
    "Pontoise": "Pontoise",
    "Port": "Port",
    "Portes-lès-Valence": "Portes-lès-Valence",
    "Portland": "Portland",
    "Porto": "Porto",
    "Prague, Brno, Ostrava": "Prague",
    "Praha": "Praha",
    "Pringy": "Pringy",
    "Puget-sur-Argens": "Puget-sur-Argens",
    "Punaauia PF": "Punaauia",
    "Puteaux": "Puteaux",
    "Périgny": "Périgny",
    "Pérols": "Pérols",
    "Quan 1": "Quan 1",
    "Quesnoy-sur-Deûle": "Quesnoy-sur-Deûle",
    "Quimper": "Quimper",
    "Quincieux": "Quincieux",
    "Quận 1": "Quận 1",
    "REAU 77": "Réau",
    "REIMS 51": "Reims",
    "RENNES 35": "Rennes",
    "RHÔNE 69": "Rhône",
    "ROCHESERVIERE 85": "Rocheservière",
    "ROISSY EN FRANCE 95": "Roissy-en-France",
    "ROUBAIX 59": "Roubaix",
    "ROUEN 76": "Rouen",
    "RUEIL MALMAISON 92": "Rueil-Malmaison",
    "RUNGIS 94": "Rungis",
    "Rabat": "Rabat",
    "Rambervillers": "Rambervillers",
    "Rambouillet": "Rambouillet",
    "Ramonville-Saint-Agne": "Ramonville-Saint-Agne",
    "Reichstett": "Reichstett",
    "Reims": "Reims",
    "Remote": "Remote",
    "Rennes": "Rennes",
    "Rezé": "Rezé",
    "Rians": "Rians",
    "Rillieux-la-Pape": "Rillieux-la-Pape",
    "Ris-Orangis": "Ris-Orangis",
    "Roanne": "Roanne",
    "Rodez": "Rodez",
    "Roissy-en-France": "Roissy-en-France",
    "Romainville": "Romainville",
    "Romilly-sur-Seine": "Romilly-sur-Seine",
    "Ronchin": "Ronchin",
    "Roost-Warendin": "Roost-Warendin",
    "Rosny-sous-Bois": "Rosny-sous-Bois",
    "Roubaix": "Roubaix",
    "Rouen": "Rouen",
    "Rouffach": "Rouffach",
    "Rousset": "Rousset",
    "Roye": "Roye",
    "Rue": "Rue",
    "Rueil-Malmaison": "Rueil-Malmaison",
    "Rungis": "Rungis",
    "Réau": "Réau",
    "Rémire-Montjoly GF": "Rémire-Montjoly",
    "SACLAY 91": "Saclay",
    "SAVOIE (HAUTE) 74": "Haute-Savoie",
    "SAVOIE 73": "Savoie",
    "SEINE SAINT DENIS 93": "Seine-Saint-Denis",
    "SEVRES 92": "Sèvres",
    "ST CLOUD 92": "Saint-Cloud",
    "ST CYR SUR LOIRE 37": "Saint-Cyr-sur-Loire",
    "ST DENIS 93": "Saint-Denis",
    "ST HERBLAIN 44": "Saint-Herblain",
    "ST JOSEPH 972": "Saint-Joseph",
    "ST LAURENT DU VAR 06": "Saint-Laurent-du-Var",
    "ST MEDARD EN JALLES 33": "Saint-Médard-en-Jalles",
    "ST OUEN SUR SEINE 93": "Saint-Ouen-sur-Seine",
    "ST PRIEST 69": "Saint-Priest",
    "ST VULBAS 01": "Saint-Vulbas",
    "STAINS 93": "Stains",
    "STRASBOURG 67": "Strasbourg",
    "SUISSE": "Suisse",
    "SURGERES 17": "Surgères",
    "Saclay": "Saclay",
    "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
    "Saint-Amand-les-Eaux": "Saint-Amand-les-Eaux",
    "Saint-André-de-Corcy": "Saint-André-de-Corcy",
    "Saint-André-lez-Lille": "Saint-André-lez-Lille",
    "Saint-Apollinaire": "Saint-Apollinaire",
    "Saint-Aubin": "Saint-Aubin",
    "Saint-Beauzire": "Saint-Beauzire",
    "Saint-Benoît": "Saint-Benoît",
    "Saint-Brieuc": "Saint-Brieuc",
    "Saint-Brès": "Saint-Brès",
    "Saint-Cannat": "Saint-Cannat",
    "Saint-Chamas": "Saint-Chamas",
    "Saint-Cloud": "Saint-Cloud",
    "Saint-Denis, Villeurbanne…+1": "Saint-Denis",
    "Saint-Denis-de-l'Hôtel": "Saint-Denis-de-l'Hôtel",
    "Saint-Didier-au-Mont-d'Or": "Saint-Didier-au-Mont-d'Or",
    "Saint-Dizier": "Saint-Dizier",
    "Saint-Dié-des-Vosges": "Saint-Dié-des-Vosges",
    "Saint-Genis-Laval": "Saint-Genis-Laval",
    "Saint-Genis-les-Ollières, Auvergne-Rhône-Alpes, France": "Saint-Genis-les-Ollières",
    "Saint-Genès-Champanelle": "Saint-Genès-Champanelle",
    "Saint-Germain-en-Laye": "Saint-Germain-en-Laye",
    "Saint-Germain-les-Belles": "Saint-Germain-les-Belles",
    "Saint-Gilles": "Saint-Gilles",
    "Saint-Herblain": "Saint-Herblain",
    "Saint-Hilaire-de-Riez": "Saint-Hilaire-de-Riez",
    "Saint-Jacques-de-la-Lande": "Saint-Jacques-de-la-Lande",
    "Saint-Jean-Cap-Ferrat": "Saint-Jean-Cap-Ferrat",
    "Saint-Jean-de-Védas": "Saint-Jean-de-Védas",
    "Saint-Jorioz": "Saint-Jorioz",
    "Saint-Julien-la-Geneste": "Saint-Julien-la-Geneste",
    "Saint-Laurent-du-Maroni": "Saint-Laurent-du-Maroni",
    "Saint-Leu-la-Forêt": "Saint-Leu-la-Forêt",
    "Saint-Léger-sous-Cholet": "Saint-Léger-sous-Cholet",
    "Saint-Léonard": "Saint-Léonard",
    "Saint-Malo": "Saint-Malo",
    "Saint-Mandé": "Saint-Mandé",
    "Saint-Marcel": "Saint-Marcel",
    "Saint-Martin-d'Hères": "Saint-Martin-d'Hères",
    "Saint-Martin-de-Crau": "Saint-Martin-de-Crau",
    "Saint-Maur-des-Fossés": "Saint-Maur-des-Fossés",
    "Saint-Maurice": "Saint-Maurice",
    "Saint-Médard-en-Jalles": "Saint-Médard-en-Jalles",
    "Saint-Même-le-Tenu": "Saint-Même-le-Tenu",
    "Saint-Nazaire": "Saint-Nazaire",
    "Saint-Ouen": "Saint-Ouen",
    "Saint-Ouen-l'Aumône": "Saint-Ouen-l'Aumône",
    "Saint-Ouen-sur-Seine": "Saint-Ouen-sur-Seine",
    "Saint-Paul RE": "Saint-Paul",
    "Saint-Paul-Trois-Châteaux": "Saint-Paul-Trois-Châteaux",
    "Saint-Paul-lès-Durance": "Saint-Paul-lès-Durance",
    "Saint-Pierre RE": "Saint-Pierre",
    "Saint-Pierre-d'Irube": "Saint-Pierre-d'Irube",
    "Saint-Pierre-des-Corps": "Saint-Pierre-des-Corps",
    "Saint-Priest": "Saint-Priest",
    "Saint-Priest-sous-Aixe": "Saint-Priest-sous-Aixe",
    "Saint-Quentin-Fallavier": "Saint-Quentin-Fallavier",
    "Saint-Quentin-en-Yvelines": "Saint-Quentin-en-Yvelines",
    "Saint-Quentin-sur-le-Homme": "Saint-Quentin-sur-le-Homme",
    "Saint-Raphaël": "Saint-Raphaël",
    "Saint-Sauveur": "Saint-Sauveur",
    "Saint-Sylvain-d'Anjou": "Saint-Sylvain-d'Anjou",
    "Saint-Sébastien-sur-Loire": "Saint-Sébastien-sur-Loire",
    "Saint-Vallier": "Saint-Vallier",
    "Saint-Étienne": "Saint-Étienne",
    "Saint-Étienne-du-Rouvray": "Saint-Étienne-du-Rouvray",
    "Sainte-Consorce": "Sainte-Consorce",
    "Sainte-Geneviève-des-Bois": "Sainte-Geneviève-des-Bois",
    "Saintes": "Saintes",
    "Salon-de-Provence": "Salon-de-Provence",
    "San-Nicolao": "San-Nicolao",
    "Sannois": "Sannois",
    "Santa Clara": "Santa Clara",
    "Sassenage": "Sassenage",
    "Saumur": "Saumur",
    "Saverne": "Saverne",
    "Schiltigheim": "Schiltigheim",
    "Scionzier": "Scionzier",
    "Seclin": "Seclin",
    "Sennecey-lès-Dijon": "Sennecey-lès-Dijon",
    "Sens": "Sens",
    "Serres-Castet": "Serres-Castet",
    "Serris": "Serris",
    "Seyssinet": "Seyssinet",
    "Seyssinet-Pariset": "Seyssinet-Pariset",
    "Six-Fours-Les-Plages": "Six-Fours-Les-Plages",
    "Six-Fours-les-Plages": "Six-Fours-les-Plages",
    "Sofia": "Sofia",
    "Soissons": "Soissons",
    "Solaize": "Solaize",
    "Sophia Antipolis": "Sophia Antipolis",
    "Sophia-Antipolis": "Sophia-Antipolis",
    "Soufflenheim": "Soufflenheim",
    "Stains": "Stains",
    "Strasbourg": "Strasbourg",
    "Stuttgart": "Stuttgart",
    "Suresnes": "Suresnes",
    "Sète": "Sète",
    "Sèvremoine": "Sèvremoine",
    "Sèvres": "Sèvres",
    "Sélestat": "Sélestat",
    "Sézanne": "Sézanne",
    "TARBES 65": "Tarbes",
    "TARN 81": "Tarn",
    "TOULON 83": "Toulon",
    "TOULOUSE 31": "Toulouse",
    "TOURS 37": "Tours",
    "TREMBLAY EN FRANCE 93": "Tremblay-en-France",
    "Taden": "Taden",
    "Taipei City": "Taipei City",
    "Talence": "Talence",
    "Tallinn": "Tallinn",
    "Tarascon": "Tarascon",
    "Tarbes": "Tarbes",
    "Tarnos": "Tarnos",
    "Tassin-la-Demi-Lune, Paris…+1": "Tassin-la-Demi-Lune",
    "Tel Aviv-Yafo": "Tel Aviv-Yafo",
    "Templemars": "Templemars",
    "Termoli": "Termoli",
    "Theix-Noyalo": "Theix-Noyalo",
    "Thillois": "Thillois",
    "Thionville": "Thionville",
    "Thouaré-sur-Loire": "Thouaré-sur-Loire",
    "Tillé": "Tillé",
    "Tinqueux": "Tinqueux",
    "Tinténiac": "Tinténiac",
    "Torcy": "Torcy",
    "Toronto": "Toronto",
    "Toulon": "Toulon",
    "Toulouse, Bordeaux": "Toulouse",
    "Tour-en-Sologne": "Tour-en-Sologne",
    "Tours": "Tours",
    "Trappes": "Trappes",
    "Tremblay-en-France": "Tremblay-en-France",
    "Troyes": "Troyes",
    "Trélazé": "Trélazé",
    "Tunis, Monastir": "Tunis",
    "Turckheim": "Turckheim",
    "Télétravail": "Télétravail",
    "Uchaud": "Uchaud",
    "Utrecht": "Utrecht",
    "VAL DE MARNE 94": "Val-de-Marne",
    "VALBONNE 06": "Valbonne",
    "VANNES 56": "Vannes",
    "VANVES 92": "Vanves",
    "VAR 83": "Var",
    "VELIZY VILLACOUBLAY 78": "Vélizy-Villacoublay",
    "VILLEJUIF 94": "Villejuif",
    "VILLEMUR SUR TARN 31": "Villemur-sur-Tarn",
    "VILLENEUVE D ASCQ 59": "Villeneuve-d'Ascq",
    "VILLEURBANNE 69": "Villeurbanne",
    "VINCENNES 94": "Vincennes",
    "Vaison-la-Romaine": "Vaison-la-Romaine",
    "Val-de-Reuil": "Val-de-Reuil",
    "Valbonne": "Valbonne",
    "Valence": "Valence",
    "Valenciennes": "Valenciennes",
    "Vallauris": "Vallauris",
    "Valserhône": "Valserhône",
    "Vandœuvre-lès-Nancy": "Vandœuvre-lès-Nancy",
    "Vannes": "Vannes",
    "Vaulx-en-Velin": "Vaulx-en-Velin",
    "Vendargues": "Vendargues",
    "Venelles": "Venelles",
    "Venette": "Venette",
    "Verdun": "Verdun",
    "Vern-sur-Seiche": "Vern-sur-Seiche",
    "Vernaison": "Vernaison",
    "Verneuil-en-Halatte": "Verneuil-en-Halatte",
    "Vernon": "Vernon",
    "Vertou": "Vertou",
    "Veynes": "Veynes",
    "Vieillevigne": "Vieillevigne",
    "Vienna": "Vienna",
    "Vienne": "Vienne",
    "Villard-Bonnot": "Villard-Bonnot",
    "Villaroche": "Villaroche",
    "Villecresnes": "Villecresnes",
    "Villefranche-sur-Mer": "Villefranche-sur-Mer",
    "Villefranche-sur-Saône": "Villefranche-sur-Saône",
    "Villejuif": "Villejuif",
    "Villejust": "Villejust",
    "Villemur-sur-Tarn": "Villemur-sur-Tarn",
    "Villenave-d'Ornon": "Villenave-d'Ornon",
    "Villeneuve-D'ascq": "Villeneuve-d'Ascq",
    "Villeneuve-Loubet": "Villeneuve-Loubet",
    "Villeneuve-d'Ascq": "Villeneuve-d'Ascq",
    "Villeneuve-la-Garenne": "Villeneuve-la-Garenne",
    "Villennes-sur-Seine": "Villennes-sur-Seine",
    "Villeparisis": "Villeparisis",
    "Villers-Bretonneux": "Villers-Bretonneux",
    "Villers-Cotterêts": "Villers-Cotterêts",
    "Villers-lès-Nancy": "Villers-lès-Nancy",
    "Villetaneuse": "Villetaneuse",
    "Villeurbanne": "Villeurbanne",
    "Villiers-Saint-Fréderic": "Villiers-Saint-Fréderic",
    "Villiers-sur-Marne": "Villiers-sur-Marne",
    "Villy-le-Pelloux": "Villy-le-Pelloux",
    "Vilnius": "Vilnius",
    "Vincennes": "Vincennes",
    "Viroflay": "Viroflay",
    "Vitrolles": "Vitrolles",
    "Vitry-sur-Seine": "Vitry-sur-Seine",
    "Vitré": "Vitré",
    "Vittel": "Vittel",
    "Vizille": "Vizille",
    "Voisins-le-Bretonneux": "Voisins-le-Bretonneux",
    "Voreppe": "Voreppe",
    "Vélizy-Villacoublay": "Vélizy-Villacoublay",
    "Vénissieux": "Vénissieux",
    "Vézénobres": "Vézénobres",
    "Wambrechies": "Wambrechies",
    "Warsaw": "Warsaw",
    "Wasquehal": "Wasquehal",
    "Wattrelos": "Wattrelos",
    "Wettolsheim": "Wettolsheim",
    "Willems": "Willems",
    "Winter Haven": "Winter Haven",
    "Wissembourg": "Wissembourg",
    "Woluwé-Saint-Lambert": "Woluwé-Saint-Lambert",
    "Woodbridge": "Woodbridge",
    "YVELINES 78": "Yvelines",
    "Ymare": "Ymare",
    "Yuty": "Yuty",
    "Zug": "Zug",
    "Échirolles": "Échirolles",
    "Écully": "Écully",
    "Éguilles": "Éguilles",
    "Élancourt": "Élancourt",
    "Épaux-Bézu": "Épaux-Bézu",
    "Éragny": "Éragny",
    "Étrelles": "Étrelles",
    "Évian-les-Bains": "Évian-les-Bains",
    "Évreux": "Évreux",
    "Évry": "Évry",
    "Évry-Courcouronnes": "Évry-Courcouronnes",
    "Île-de-France": "Île-de-France"
}

def process_location(location, dictionnaire):
    if location is not None:
        location = location.strip()
        if location in dictionnaire:
            return dictionnaire[location]
        return location
    return location

def find_job_title(title, jobs_dict):
    title_lower = title.lower()
    for job, keywords in jobs_dict.items():
        if isinstance(keywords[0], tuple):
            for keyword_tuple in keywords:
                if all(word in title_lower for word in keyword_tuple):
                    return job
        else:
            if all(word in title_lower for word in keywords):
                return job
    return "Other"

def nettoyer_experience(liste):
    if liste is None:
        return None
    nettoye = [mot for mot in liste if mot is not None and mot.lower().strip() not in {'a', 'n', 's'}]
    return nettoye

def process_experience(experience):
    experience = experience.lower()
    if "débutant accepté" in experience:
        return "débutant accepté"
    mois_match = re.search(r'(\d+)\s*mois', experience)
    if mois_match:
        return f"{mois_match.group(1)} mois"
    annees_match = re.search(r'(\d+)\s*(?:an|ans|année|années|year|years?)', experience)
    if annees_match:
        return f"{annees_match.group(1)} an(s)"
    comparaison_match = re.search(r'[<>]\s*(\d+)(?:\s*(?:an|ans|année|années|year|years?))?', experience)
    if comparaison_match:
        return f"{comparaison_match.group(1)} an(s)"
    nombre_match = re.search(r'\d+', experience)
    if nombre_match:
        return f"{nombre_match.group(0)} an(s)"
    return experience

def transform_list_to_string(liste):
    if isinstance(liste, list):
        return ', '.join(liste)
    return liste

def find_keywords(description, keywords):
    found_keywords = set()
    description_lower = description.lower()
    for keyword in keywords:
        keyword_lower = keyword.strip().lower()
        if re.search(r'\b' + re.escape(keyword_lower) + r'\b', description_lower):
            found_keywords.add(keyword.strip())
    return list(found_keywords)

def transform_json_file(input_file, output_folder, log_file_path):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    with open(log_file_path, 'w', encoding='utf-8') as log_file:
        if input_file.endswith(".json"):
            with open(input_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            for entry in data:
                if 'raw_description' in entry:
                    entry['description'] = entry.pop('raw_description')
                title = entry.pop('title', '')
                if title:
                    entry['job_title'] = find_job_title(title.lower(), JOBS)
                else:
                    entry['job_title'] = "Other"
                entry['title'] = entry.pop('job_title')
                if 'location' in entry:
                    before_location = entry['location']
                    entry['location'] = process_location(entry['location'], places)
                    after_location = entry['location']
                    print(f"Avant transformation: {before_location}", file=log_file)
                    print(f"Après transformation: {after_location}", file=log_file)
                else:
                    entry['location'] = None
                if "details" not in entry or entry["details"] is None:
                    entry["details"] = {}
                details = entry["details"]
                if "job_detail" in entry:
                    details["JoDetail"] = entry.pop("job_detail")
                if "contract_type" in entry:
                    details["TypeContract"] = entry.pop("contract_type")
                if "salary" in entry:
                    details["Salary"] = entry.pop("salary")
                if "education_level" in entry:
                    details["Level"] = entry.pop("education_level")
                if "experience" in entry:
                    details["Experience"] = entry.pop("experience")
                if "skills" in entry:
                    del entry["skills"]
                if "link" not in entry:
                    entry["link"] = None
                if "details" in entry and "Experience" in entry["details"] and not isinstance(entry["details"]["Experience"], list):
                    entry["details"]["Experience"] = [entry["details"]["Experience"]]
                if "details" in entry and "Experience" in entry["details"]:
                    experience_list = entry["details"]["Experience"]
                    cleaned_experience = nettoyer_experience(experience_list)
                    if isinstance(cleaned_experience, list):
                        transformed_experience = [process_experience(exp) for exp in cleaned_experience]
                        entry["details"]["Experience"] = ', '.join(set(exp.lower() for exp in transformed_experience if exp))
                if "details" in entry:
                    for key in ["Experience", "TypeContract", "Salary", "Level"]:
                        if key in entry["details"] and entry["details"][key] == "":
                            entry["details"][key] = None
                if "details" in entry:
                    for key in ["TypeContract", "Salary", "Level"]:
                        if key in entry["details"]:
                            entry["details"][key] = transform_list_to_string(entry["details"][key])
                description = entry.get('description', '')
                if description:
                    entry['skills'] = {}
                    for variable, keywords in skills.items():
                        found_keywords = find_keywords(description, keywords)
                        if found_keywords:
                            entry['skills'][variable] = found_keywords
            output_filepath = os.path.join(output_folder, f"{os.path.splitext(os.path.basename(input_file))[0]}_updated.json")
            with open(output_filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)

    log_file.close()
    print("Les données mises à jour ont été sauvegardées.")

def process_all_files_in_directory(input_folder, output_folder, log_file_path):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    json_files = [f for f in os.listdir(input_folder) if f.endswith(".json")]
    
    with open(log_file_path, 'w', encoding='utf-8') as log_file:
        for json_file in json_files:
            input_file_path = os.path.join(input_folder, json_file)
            print(f"Processing file: {input_file_path}")
            transform_json_file(input_file_path, output_folder, log_file_path)

# pour test ou de debug.
# if __name__ == "__main__":
#     process_all_files_in_directory("path/to/input", "path/to/output", "path/to/log")